import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { cn } from "@/lib/utils";
export const metadata: Metadata = {
   title: "Alooh Electrical",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en" className={cn("h-full", "antialiased")}>
         <body className="min-h-full flex flex-col" suppressHydrationWarning={true}>
            <Navbar />
            <main className=" flex-1">{children}</main>
            <Footer />
         </body>
      </html>
   );
}
