import type { Metadata } from "next";
import { Linden_Hill, Quattrocento_Sans, Geist } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { cn } from "@/lib/utils";

const LindenHill = Linden_Hill({
  variable: "--font-Linden_Hill",
  weight: ["400"],
  subsets: ["latin"],
});

const QuattrocentoSans = Quattrocento_Sans({
  variable: "--font-Quattrocento_Sans",
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "New Orient",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        LindenHill.variable,
        QuattrocentoSans.variable,
        "font-sans",
      )}
    >
      <body
        className="min-h-full flex flex-col"
        suppressHydrationWarning={true}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
